build:
  binary: clickhouse_sinker
  main: ./cmd/clickhouse_sinker
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
  flags:
    - -tags=sqlite

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "checksums.txt"

nfpms:
  - vendor: clickhouse_sinker
    homepage: https://github.com/viru-tech/clickhouse_sinker
    maintainer: VIRU developers
    description: Sinker program that transfer kafka message into ClickHouse.
    license: MIT
    formats:
      - deb
      - rpm
    file_name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
