version: 2
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - id: clickhouse_sinker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/clickhouse_sinker
    binary: clickhouse_sinker
  - id: nacos_publish_config
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/nacos_publish_config
    binary: nacos_publish_config
checksum:
  name_template: checksums.txt
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
