{
 "title": "clickhouse_sinker_new",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "task", "label": "task", "query": { "query": "label_values(task)" } },
   { "name": "topic", "label": "topic", "query": { "query": "label_values(topic)" } },
   { "name": "consumer", "label": "consumer", "query": { "query": "label_values(consumer)" } }
  ]
 },
 "panels": [
  { "title": "Clickhouse-sinker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "datasource" },
  {
   "title": "clickhouse_sinker_consume_msgs_total rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by(task)(rate(clickhouse_sinker_consume_msgs_total{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}[1m])))"
    }
   ]
  },
  {
   "title": "clickhouse_sinker_writing_pool_backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by(task) (clickhouse_sinker_writing_pool_backlog{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}))"
    }
   ]
  },
  {
   "title": "clickhouse_sinker_flush_msgs_total rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by(task) (rate(clickhouse_sinker_flush_msgs_total{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}[1m])))"
    }
   ]
  },
  {
   "title": "clickhouse_sinker_shard_msgs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by(task) (clickhouse_sinker_shard_msgs{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}))"
    }
   ]
  },
  {
   "title": "clickhouse_sinker_parse_msgs_error_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(task)(rate(clickhouse_sinker_parse_msgs_error_total{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}[1m]))"
    }
   ]
  },
  {
   "title": "clickhouse_sinker_flush_msgs_error_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by(task)(rate(clickhouse_sinker_flush_msgs_error_total{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}[1m])))"
    }
   ]
  },
  {
   "title": "committed offset",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " {instance=~\"${instance}\",job=~\"${job}\",topic=~\"${topic}\",consumer=~\"${consumer}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "clickhouse_sinker_consume_lags",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "clickhouse_sinker_consume_lags{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\",consumer=~\"${consumer}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "clickhouse_sinker_write_series_*",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clickhouse_sinker_write_series_allow_changed{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "clickhouse_sinker_write_series_allow_new{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "clickhouse_sinker_write_series_drop_quota{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "clickhouse_sinker_write_series_drop_unchanged{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "clickhouse_sinker_write_series_succeed{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "clickhouse_sinker_writing_durations_bucket",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "ceil(increase(clickhouse_sinker_writing_durations_bucket{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\",le!=\"+Inf\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "clickhouse_sinker_writing_durations_average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(clickhouse_sinker_writing_durations_sum{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}[1m]) / rate(clickhouse_sinker_writing_durations_count{instance=~\"${instance}\",job=~\"${job}\",task=~\"${task}\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Process_*", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "process_resident_memory_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"${instance}\",job=~\"${job}\"}[1m])*100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go_*", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "go_memstats_alloc_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_alloc_bytes_total{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_parallelism",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_threads{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_heap_*_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_released_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"${instance}\",job=~\"${job}\"} + go_memstats_heap_idle_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_stack_*_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_gc_*_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_gc_sys_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=~\"${instance}\",job=~\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}