FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
RUN echo "UTC" >  /etc/timezone
ADD dist/clickhouse_sinker_linux_amd64/clickhouse_sinker /usr/local/bin/clickhouse_sinker
ADD dist/nacos_publish_config_linux_amd64/nacos_publish_config /usr/local/bin/nacos_publish_config

# clickhouse_sinker gets config from local file "/etc/clickhouse_sinker.json" by default.
# Customize behavior with following env variables:
# - V
# - HTTP_PORT
# - METRIC_PUSH_GATEWAY_ADDRS
# - PUSH_INTERVAL
# - LOCAL_CFG_FILE
# - NACOS_ADDR
# - NACOS_USERNAME
# - NACOS_PASSWORD
# - NACOS_NAMESPACE_ID
# - NACOS_GROUP
# - NACOS_DATAID
# See cmd/clickhouse_sinker/main.go for details.

ENTRYPOINT ["/usr/local/bin/clickhouse_sinker"]
