name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Start docker-compose
      run: |
        docker-compose --version
        docker-compose up -d

    - name: Build
      run: make build

    - name: unittest
      run: make unittest

    - name: benchtest
      run: make benchtest

    - name: systest
      run: make systest

    - name: Stop docker-compose
      run: docker-compose down
